version: "3.8"

services:
  server:
    image: iperf3-test
    command: iperf3 -s
    ports:
      - "5201:5201"
    networks:
      nettest:
        ipv4_address: 172.30.0.2

  client:
    image: iperf3-test
    command: iperf3 -c 172.30.0.2 -p 5201 --no-delay -t 10 && sleep infinity
    networks:
      nettest:
        ipv4_address: 172.30.0.3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"

networks:
  nettest:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
