services:
  base: &base
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: tcpxudp
    cap_add:
      - NET_ADMIN
    volumes:
      - ./volumes/iperf:/volumes/iperf

  iperf-server:
    <<: *base
    entrypoint: iperf3 -s

  200mbps:
    <<: *base
    environment:
      - NETWORK_SPEED=200
    depends_on:
      - iperf-server        
    # command: iperf3 -c iperf-server -w 256K -M 9000 -t 30 --logfile /volumes/iperf/200-tcp.txt && \
    #           iperf3 -c iperf-server -w 256K -M 9000 -t 30 -u --logfile /volumes/iperf/200-udp.txt

  500mbps:
    <<: *base
    environment:
      - NETWORK_SPEED=500
    depends_on:
      - iperf-server
    # command: iperf3 -c iperf-server -w 256K -M 9000 -t 30 --logfile /volumes/iperf/500-tcp.txt && \
    #           iperf3 -c iperf-server -w 256K -M 9000 -t 30 -u --logfile /volumes/iperf/500-udp.txt

  700mbps:
    <<: *base
    environment:
      - NETWORK_SPEED=700
    depends_on:
      - iperf-server
    # command: iperf3 -c iperf-server -w 256K -M 9000 -t 30 --logfile /volumes/iperf/700-tcp.txt && \
    #           iperf3 -c iperf-server -w 256K -M 9000 -t 30 -u --logfile /volumes/iperf/700-udp.txt

  1gbps:
    <<: *base
    environment:
      - NETWORK_SPEED=1000
    depends_on:
      - iperf-server
    # command: iperf3 -c iperf-server -w 256K -M 9000 -t 30 --logfile /volumes/iperf/1000-tcp.txt && \
    #           iperf3 -c iperf-server -w 256K -M 9000 -t 30 -u --logfile /volumes/iperf/1000-udp.txt